use_frameworks!

platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:GuoZhiQiang/RNRepos.git'

target 'QQReact_Example' do
  pod 'QQReact', :path => '../'

  target 'QQReact_Tests' do
    inherit! :search_paths

    
  end
end
